version: '3.7'
services: # 여러 컨테이너를 정의하는데 사용됨
  nestjs-app:
    build: . # 이미지를 대신함. Dockerfile 경로를 설정해서 직접 띄울때
    ports: # 호스트와 컨테이너의 포트 바인딩 설정에 사용됨 
      - "3000:3000"
    volumes: # 호스트의 지정된 경로로 컨테이너의 볼륨을 마운트 하도록 설정
      - ./nestapp:/var/app
    depends_on:
      - oracle-db
    env_file:
      - .env

  oracle-db:
    image: jaspeen/oracle-11g:latest # 이미지 정의
    contaniner_name: oracle11g
    ports:
      - "1521:1521"
    env_file:
      - .env

