version: '3.8'
services:
  tdd_server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
    networks:
      - app-tier
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxiDB
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - app-tier
    volumes:
      - ./db/postgres:/var/lib/postgres
      - ./postgres/:/docker-entrypoint-initdb.d/

volumes:
  postgres:
    driver: local

networks:
  app-tier:
    driver: bridge
