version: '3.8'
services:
  tdd_server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      - name=value
    networks:
      - app-tier
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    restart: always
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxiDB
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - app-tier
    volumes:
      - ./db/postgresql:/var/lib/postgresql
      - ./postgresql/:/docker-entrypoint-initdb.d/

volumes:
  mysql:
    driver: local

networks:
  app-tier:
    driver: bridge
