name: Pipeline Alpha
run-name: ${{ github.actor }} running alpha CI 🚀
on:
  push:
    branches: [chore/*, feature/*, fix/*, hotfix/*]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i yarn

      - name: Build
        run: yarn build --if-present

      - name: Run tests
        run: yarn test
